"""empty message

Revision ID: 03018912142d
Revises: 287fb74eac4f
Create Date: 2020-03-22 19:19:42.844678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03018912142d'
down_revision = '287fb74eac4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum', sa.Column('theme', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum', 'theme')
    # ### end Alembic commands ###
