"""reviews and scores

Revision ID: 287fb74eac4f
Revises: cc3c679e2288
Create Date: 2020-02-14 09:23:59.574384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '287fb74eac4f'
down_revision = 'cc3c679e2288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'content',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'content',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               nullable=True)
    # ### end Alembic commands ###
